build.js
package-lock.json
package.json
serve.js
src/components/Player/Player.tsx
src/index.tsx
tsconfig.json

2 main victories of this PR are:
- More standard `tsconfig.json` file
- Package now builds and imports successfully
To test a local import:
1. In this local project directory run `yarn link`
2. Fire up a test consuming app.  Or start a new Create React App if you want `npx create-react-app throwaway-consumer`
3. In consuming app terminal window, locally import our dev component.  `npm i /path/to/your/react-media-player` 
4. Copy and paste the output the `yarn link` command gives to link your local package.
If you're using create react app, you'll see an Invalid Hook error cause due to duplicate React copies being referenced.  We'll make our `react-media-player` code use the consuming app's `react` package.
`cd` back to the `react-media-player` directory and run:
```
npm link …
```

Update build and packaging config

---

src/components/Media/Media.tsx
src/components/Media/MediaItem.tsx
src/index.tsx
src/services/iiif.ts
src/services/utils.test.ts
src/services/utils.ts

This pull request lays the ground work for rendering out canvases as individual `<MediaItem/>` in the `<Media/>` component. 
It introduces a function `getCanvasByCriteria()` that we may want to treat as a _hook_. This filters out canvases that do not match a specified W3C annotation motivation ("painting", "supplementing"), or content resource type ("Image", "Sound", "Video").
Additionally, some work was completed to indicate to the end user visually which active media item is set.

Render Media Component

---

public/badManifest.json
src/components/Media/MediaItem.test.tsx
src/components/Media/MediaItem.tsx
src/hooks/use-hyperion-framework/getCanvasByCriteria.ts
src/hooks/use-hyperion-framework/getThumbnail.ts

Round one of some code which will help keep the app from crashing if it runs into parsing errors.
I committed a file in /public which is a bad manifest.  You can feed that into `dev.tsx` as the `manifestId` to render the bad manifest and see if the app loads.

Update some defensive code around parsing the manifest

---

public/index.html
src/components/Media/Media.tsx
src/components/Media/MediaItem.tsx
src/components/Navigator/Navigator.tsx
src/components/Navigator/NavigatorCue.tsx
src/components/Navigator/NavigatorTab.tsx
src/components/Player/Player.tsx
src/components/Viewer/Viewer.tsx
src/theme.tsx

This pull request refines the styling of the RMP app:
- adds variable based colors, fonts, and transitions using stitches theming, naming colors with the thought that these might someday be used for multiple _modes_.
- defines font sizes for various selectors resolving small font sizes issues for the media item labels and the navigator cue text.
- adds a pure CSS spinning indicator for active cue item (this is just styled for now and set to the first child) actual work for active cue item will occur in [2188](https://github.com/nulib/repodev_planning_and_docs/issues/2188)
- adds a pure CSS play indicator on hover of a navigator cue
- includes the Northwestern font imports in the `public/index.html` for a better dev experience
If you have thoughts on a better location for `theme.tsx`, I'm …

Refine styling of RMP.

---

public/index.html
src/components/Navigator/Navigator.tsx

This is a quick PR to fix the background header issue brought about by an [accidental deletion](https://github.com/nulib/react-media-player/commit/adef7f2d06d22b83b42c583384531e2a0d4345d7#diff-81b646d5970f79ecff67d8f74a04f5bb65705eb33168a528cbe081442d3f9a60L67) in #23.
**Issue**
**Fix**

Fix header background inheritance issue.

---

package-lock.json
package.json
public/fixtures/iiif/manifests/assortedCanvases.json
src/components/ImageViewer/Button.styled.tsx
src/components/ImageViewer/Button.test.tsx
src/components/ImageViewer/Button.tsx
src/components/ImageViewer/Controls.styled.tsx
src/components/ImageViewer/Controls.test.tsx
src/components/ImageViewer/Controls.tsx
src/components/ImageViewer/ImageViewer.styled.tsx
src/components/ImageViewer/ImageViewer.test.tsx
src/components/ImageViewer/ImageViewer.tsx
src/components/Media/Media.tsx
src/components/Media/Thumbnail.tsx
src/components/Navigator/Navigator.tsx
src/components/Viewer/Viewer.tsx
src/hooks/use-hyperion-framework/getResourceType.ts
src/stitches.tsx

This pull request brings in the OpenSeadragon viewer into the RMP package for viewing of Image based canvases. Functionality for this is limited to zoom in, zoom out and reset of the viewer. All controls are entirely keyboard operable. Upon switching canvases, the item should render centered in the OpenSeadragon canvas. The instance will remain intact while toggling image canvases and will destroy itself when the user toggles to a non-Image canvas.

Add pan-zoom feature for Image canvases.

---

README.md

Updates the Readme docs to explain what the `options` prop does.

Update Readme documentation for options config prop

---

build.js
package.json

Update build config to add build command to npm publishing automatically.  Also converted all dependencies to externals, to force consuming apps to install the dependencies, reducing the weight of our package.
Now when we run `npm publish`, it'll pre-build the package which `npm` includes in it's tarball.

Update build config 

---

package-lock.json
package.json
src/components/Media/Thumbnail.styled.tsx
src/components/Media/Thumbnail.tsx

This pull request adds work/resource type icons to the media thumbnails for Audio (Sound), Image, and Video. To implement, I merged it with the previously existing `<Duration/>` component. Now all canvas types will have some sort of `<Type>`  with an embedded `<Icon>` (from `@nulib/design-system`), and Audio/Video works will show duration as a label.
- Add resource type icons to Media thumbnails.
- Add in some transparency.
- Add IconPath and switch statement.

Add resource type icons to thumbnails.

---

public/index.html
src/components/ImageViewer/Button.styled.tsx

This fixes a minor issue related to box-sizing of the OpenSeadragon image viewer controls when the RMP component is embedded into a consuming app. RMP now hardcodes this value to avoid any issues with distortion of svgs embedded within a `<button>` element.

Hardcode boxSizing for open seadragon controls.

---

src/components/ImageViewer/Button.styled.tsx

This is a quick fix that adds an `!important` to ensure box-sizing attribute is set to `content-box` on button icons in the OpenSeadgraon control.

Make content-box even more explicit.

---

package-lock.json
package.json
public/index.html
src/components/ImageViewer/ImageViewer.styled.tsx
src/components/ImageViewer/ImageViewer.tsx
src/components/Media/Media.styled.tsx
src/components/Media/Thumbnail.styled.tsx
src/components/Navigator/Cue.styled.tsx
src/components/Navigator/Navigator.styled.tsx
src/components/Player/Player.styled.tsx
src/components/Viewer/Viewer.styled.tsx
src/components/Viewer/Viewer.tsx
src/hooks/useBodyLocked.ts
src/hooks/useMediaQuery.ts
src/stitches.tsx

The work included here adds baseline responsive behavior to the project. Most of this is based around a specific breakpoint of `sm` defined in the stitches configuration file. When this breakpoint is reached and true, the navigator (if present) collapse under the Player and Media elements. 
By default the navigator will not be displayed, however, toggle with the title **View Navigator** will be shown to the user on canvases where the Navigator is available. When expanded, the player goes into a emulated modal state where navigator contents are shown and scrollable. This behavior exists to limit the possibility of multiple scrollbars. When the user clicks **Media Items**, scrolling functionality on the consuming page is present once again.
Included as well are various touchups to refine …

Baseline responsiveness.

---

src/components/Navigator/Cue.styled.tsx
src/components/Viewer/Viewer.styled.tsx
src/hooks/useBodyLocked.ts

This fixes a few small issues that I uncovered after importing v.1.6.0 into the Meadow and Digital Collections. Completing these should make the next patched version ready for deploy/staging on both applications.
**- Fix zIndex issue** - Present in both Meadow and DC where the expanded navigator on small viewports did not layer above relative or absolute content elsewhere on the page. This is set to an extreme value to ensure it lives over Radix UI portalled content.
- Fix cue flex-grow - Occurred when VTT cues did not extend beyond the vertical space. 
- Fix overflow bug - The body.overflow selector was not specific enough for Meadow or DC so moved this up a level to the HTML element.
- Fix button span child selector - This is a fix to make things a bit more explicit when targeting the …

Responsive bug fixes.

---

src/components/Navigator/Resource.tsx

CodeSandbox was giving an ugly error due to how we were requiring the node-webvtt package. To fix, we are now importing `parse` from the package and including a `// @ts-ignore` to tone down the typescript screaming.
Things should run just as before locally, and the compiled build should be compatible with CodeSandbox.

Fixes import of node-webvtt package, ignores ts scream.

---

src/components/ImageViewer/ImageViewer.tsx
src/services/iiif.ts

This pull request resolves and issue where some IIIF Image Services do not redirect to the info.json and thus do not hand off the tilesource json if the image service ID is directly handed to OpenSeadragon. This PR includes code that will request the rewrite the image service ID URI using regex (appending info.json) and then request the tilesource json first, then hand that promised json to OSD. If this fails to resolve, then a console error is displayed. This is similar logic to how Mirador seems to handle this issue.
This PR includes a sample National Library of Scotland manifest that was previously failing to load in OpenSeadragon. It should now display as expected.

Request tilesource from iiif service.

---

src/components/ImageViewer/Button.styled.tsx
src/components/Media/Filter.styled.tsx
src/components/Media/Filter.tsx
src/components/Media/Media.tsx
src/components/Media/Thumbnail.styled.tsx
src/hooks/use-hyperion-framework/getLabel.ts
src/hooks/useKeyPress.ts

This introduces basic search/filter functionality to the Viewer, allowing as user to filter the string value of the canvas label. The search button toggles and auto-focuses an input for a user to input this value. Upon filtering, the media items in the `<Media />` component are filtered and mapped. A close button is rendered allowing the user to toggle this off. Upon closing, the filter value is reset. Hitting the `esc` "Escape" keyboard button will close filter input as well. 
This filtering is pretty basic and somewhat requires the manifest canvases to have label values useful the the user. This does not filter by index or canvas number, in cases where a user might expect typing "10" would take them to the 10th canvas, unless of course the label for that canvas contained "10" within …

Add ability to search/filter canvases by label.

---

package-lock.json
package.json
src/components/Viewer/ErrorFallback.styled.tsx
src/components/Viewer/ErrorFallback.test.tsx
src/components/Viewer/ErrorFallback.tsx
src/components/Viewer/Viewer.tsx

This PR wraps the main Viewer in a React Error Boundary to prevent non-network related crashes of the app in the browser.   If there's a need in the future, we can wrap parts of the app in their own Error Boundaries (ie. Player, Media Tray, Navigator, etc.)
In some child component, initiate a syntax error, or insert a `throw new Error("hey I just errored")`.  Notice the Error Boundary catches the error.

Wrap the Viewer in an Error Boundary

---

public/fixtures/iiif/manifests/sample.json
src/components/Player/Player.tsx
src/dev.tsx

This will disable autoplay for Sound and Video canvases on initial render. It does so by not running `play()` if **startTime** is _0_. It retains the ability to automatically play if a user clicks a cue in the navigator.

Disable autoplay on initial canvas load.

---

src/components/Player/Track.tsx

This just tightens up some code and removes a duplicate `getLabel()` call on the returned `<track>`.

Remove duplicate getLabel call on track return.

---

public/fixtures/iiif/manifests/audio-accompanying-canvas.json
src/components/Player/Player.tsx
src/dev.tsx
src/hooks/use-hyperion-framework/getAccompanyingCanvasImage.test.ts
src/hooks/use-hyperion-framework/getAccompanyingCanvasImage.ts
src/hooks/use-hyperion-framework/getCanvasByCriteria.ts
src/hooks/use-hyperion-framework/index.ts
src/index.tsx

@mathewjordan Would like to chat on this...about 1.) Hyperion shortcut parsing and 2.) Setting up hooks and leaf level components to be tested easier (ie. maybe not passing in `vault`, which is hard if not impossible to mock in tests).
This PR supports Audio placeholder images when pulled in via `accompanyingCanvas` in a IIIF Manifest

2416 audio placeholder canvas

---

README.md
build-static.js
package-lock.json
package.json
public/styles.css
src/stitches.tsx
utils/html.js
utils/markdown.js

- Adjust styling.
- Add shiki highlighter, remove highlight.js, refine styling.
- Prop table styling.
- Adjust docs `<a>` color.
- Tidy up docs markdown and html writing.
This makes font and color choices generic, swaps out Highlight.js for [shiki](https://github.com/shikijs/shiki/), and cleans up documentation look and feel overall.
1. Pull down the branch
2. run `npm run build:static`
3. run `npx serve static`

Documentation style refinements and syntax highlighter swap.

---

jest-setup.ts
package-lock.json
package.json
src/components/ImageViewer/ImageViewer.test.tsx
src/components/Player/Player.test.tsx
src/hooks/use-hyperion-framework/getThumbnail.test.ts
src/services/iiif-test-fixtures.ts

Hey @mathewjordan this gets the test failures down to 2, and I've also commented them out so at least `npm run test` will now be green if we want to wire in test running in Github.

Fix a few more failing tests

---

src/components/ImageViewer/ImageViewer.tsx
src/dev.tsx
src/dev/DynamicUrl.styled.tsx
src/dev/DynamicUrl.tsx
src/dev/manifests.ts

- Initial for dynamic url setup
- Add styling and organize dev components.
- Fix type issue on input ref.
This adds an input form to update manifest IDs in the example Clover app. I also curated a small set of manifests that showcased Clover functionality and organized them as buttons.
1. Pull down the branch
2. run `npm run build:static`
3. run `npx serve static`

Add dynamic manifest url logic and examples.

---

README.md
public/styles.css
src/components/ImageViewer/ImageViewer.styled.tsx
src/components/ImageViewer/OSD.tsx
src/components/Media/Controls.styled.tsx
src/components/Media/Media.styled.tsx
src/components/Media/Thumbnail.styled.tsx
src/components/Player/Player.styled.tsx
src/components/Player/Player.tsx
src/components/Viewer/Content.tsx
src/components/Viewer/Header.styled.tsx
src/components/Viewer/Header.tsx
src/components/Viewer/Viewer.styled.tsx
src/components/Viewer/Viewer.tsx
src/context/viewer-context.tsx
src/dev.tsx

- Add basic classes for selector styling.
- More flexible styling for consuming app containers.
This adds two new config options for managing height and background color of the active canvas. These values are fed into the viewer context and distilled down to the video player and OpenSeadragon for respective content resources types. 
I also refreshed some styling choices that made to make Clover much more flexible in consuming applications.
- Added basic `clover-*` class names to some high level layout elements
- Removed padding wrapping entire app so that Clover reaches the edges of the container in the consuming application
- Replaced `<section>` wrapping element with a generic `<div>`
- **and** Cleaned up some responsive behavior on the media thumbnails

Add config options for active canvas and styling flexibility.

---

README.md
src/components/ImageViewer/OSD.tsx
src/context/viewer-context.tsx
src/dev.tsx

This sets the default **scrollToZoom** functionality as `false` for the OpenSeadragon options. Along with this, I have included the ability for a Clover implementer to modify (with some possibility for danger) the OpenSeadragon options through the **configOptions.openSeadragon** prop.
**What doesn't this do?**
Well, the cursor can still be _captured_ currently by OpenSeadragon canvas. I believe we might need to dig into that in a separate issue as it is somewhat annoying if you're trying to scroll past the canvas and are not aware that your cursor should be outside of the bound of it to affect the body scroll.

Allow setting of OpenSeadragon Options, default scrollToZoom as false.

---

src/dev.tsx

This adds functionality to read a `iiif-content` URL parameter and set it as the `manifestId` prop for Clover on the demo/development view. Doing this should bring us a step closer to Clover being included in the **iiif.io**[ viewer matrix](https://iiif.io/api/cookbook/recipe/matrix/).
**Note** -- This does not yet accommodate Clover for [Content State Encoding](https://iiif.io/api/content-state/0.9/#6-content-state-encoding).

Add iiif-content param capability to demo page.

---

src/components/Media/Thumbnail.tsx
src/components/Navigator/Navigator.tsx
src/components/Viewer/Header.tsx

This is just a quick PR to make a minor update to Clover, using Nectar `<Label>` wherever a IIIF [label](https://iiif.io/api/presentation/3.0/#label) is rendered.
- Update manifest label.
- Replace rendered labels with Nectar component.
- Use getLabel on alt.

Use Nectar Label component where possible.

---

src/components/Navigator/About.tsx

This resolve an issue where the `id` as the innerHTML within the `<a>...</a>` for each `seeAlso` entry. The issue related to how `vault` stores resources locally by **id**, I am no making `vault.get()` request to the Redux store and grabbing the additional data for entries.
Clover uses Nectar for rendering a seeAlso, thus it will still fallback to rendering an `id` if the `label` does not exist.
I also made `homepage` render in similar way, and fixed a small typo related issue with `manifest.id` not rendering.

Address seeAlso label rendering issue.

---

README.md
src/components/ImageViewer/OSD.tsx
src/context/viewer-context.tsx

Spreads the already existing and seemingly unused `openSeadragon` property out after defaults. This will allow a user to customize their OpenSeadragon instance more fully using https://openseadragon.github.io/docs/OpenSeadragon.html#.Options.
`options.openSeadragon` now has a default of `{}` and is better documented.
Example usage:
```jsx
<CloverIIIF
id={url}
options={{
openSeadragon: {
ajaxWithCredentials: true,
},
}}
/>
```

Spread out openSeadragon options on OpenSeadragon instances (allows for ajaxWithCredentials)

---

README.md
package-lock.json
package.json
src/components/ImageViewer/OSD.tsx
src/context/viewer-context.tsx
src/dev.tsx
src/index.tsx
src/services/xhr.ts

This adds a custom fetcher to our Vault instances, and allows for the boolean option `withCredentials` to be distilled down to the `customFetcher` using axios.get().

Add custom fetcher and withCredentials.

---

src/components/ImageViewer/Button.styled.tsx
src/components/ImageViewer/Controls.styled.tsx
src/components/ImageViewer/Controls.test.tsx
src/components/ImageViewer/Controls.tsx
src/components/ImageViewer/OSD.tsx

This adds new control functionality to the OpenSeadragon image viewer in Clover. 
- Adds a full screen button
- Adds rotate left and rotate right buttons (note that the icon was previously the "reset")
- Adds a new reset icon that resembles an undo
All of these icons can also now be controlled by boolean values in options.openSeadragon:
```
showFullPageControl: boolean;
showHomeControl: boolean;
showRotationControl: boolean;
showZoomControl: boolean;
```

Add rotate and full screen controls.

---

src/components/Player/Player.tsx

This work updates the **xhrSetup** (`xhr.withCredentials`) on the HLS.js config, passing the boolean value set in the `configOptions.withCredentials` prop on the Clover component. The passing of this acts very similar to how we handle withCredential requests in sub components using OpenSeadragon.
To truly verify, we really need to be able to request along with cookies, however, as a temporary test, you can update the `withCredentials` value to `true` in dev.tsx. All HLS requests will now be completed withCredentials (see developer tools requests). My suggestion is that if this code looks good, we push out a release candidate that can be tested in our staging environment.

Add withCredentials param to xhrSetup in HLS config.

---

src/components/Viewer/Content.tsx
src/dev.tsx
src/dev/manifests.ts

This sets a conditional around the More Information button to only render if `isNavigator` is true. isNavigator is old Clover logic that determines if the particular canvas should render the VTT Navigator.

Display More Information only when necessary.

---

src/components/ImageViewer/Button.styled.tsx
src/components/ImageViewer/Controls.styled.tsx
src/components/ImageViewer/ImageViewer.styled.tsx

This adds a small styling responsive fix to orient the OpenSeadragon controls vertically at `xs` viewports. The zIndex of the Controls is also now at a higher level than the "Navigator" in the top left, assuring that the controls are always going to be clickable.

Make OSD controls more usable in smallest viewports.

---

src/components/Media/Thumbnail.styled.tsx

Well, this is a very fix that adds in WebkitBoxOrient property to work alongside the existing line clamp property. This apparently had been working in FireFox already and now should work in Safari, Chrome, and other WebKit browsers. Canvas labels are limited to 5 lines and have `...` ellipsis for overflow.
To review, see http://127.0.0.1:8080/?iiif-content=https://api.dc.library.northwestern.edu/api/v2/works/eb0af039-0fe8-4dbb-96f8-836d4b6b32db?as=iiif

Apply WebKit canvas label line clamping.

---

package-lock.json
package.json
public/fixtures/iiif/manifests/placeholderCanvas-02.json
public/fixtures/iiif/manifests/placeholderCanvas.json
src/components/ImageViewer/Button.styled.tsx
src/components/ImageViewer/Controls.styled.tsx
src/components/ImageViewer/Controls.tsx
src/components/ImageViewer/OSD.tsx
src/components/Painting/Painting.styled.tsx
src/components/Painting/Painting.tsx
src/components/Painting/Placeholder.styled.tsx
src/components/Painting/Placeholder.tsx
src/components/Painting/Toggle.styled.ts
src/components/Painting/Toggle.tsx
src/components/Player/Player.styled.tsx
src/components/Player/Player.test.tsx
src/components/Player/Player.tsx
src/components/Viewer/Content.tsx
src/dev.tsx
src/dev/manifests.ts

This brings support to Clover for IIIF Presentation API 3.0  property `placeholderCanvas` for `Canvas` resources. If a placeholderCanvas exists, the annotation body of that canvas will render in place of the Canvas. An button with an icon will display to the user indicating that clicking on the placeholderCanvas OR its toggle button will open the respective Canvas in either OpenSeadragon (Images) or a media player (Video, Sound). At this point users will be in a state of `isInteractive` being true. This will stay true until the user hits the close button toggle -- even if the user toggles through canvases on the Manifest.
- Image placeholders have a _zoom in_ icon for open, while Video and Sound will have a _play_ button.
- Video and Sound will render a toggle button that centers on the …

Support IIIF Presentation API 3.0 `placeholderCanvas`

---

src/components/Player/AudioVisualizer.styled.tsx
src/components/Player/Player.styled.tsx

This fixes an issue on Audio canvases where the visualizer canvas has overlaps the the `<video>` element playing the canvas. zIndex properties have been adjusted to ensure the audio visualizer renders below the player which has a transparent background.

Fix zIndex issue on audio (sound) canvases.

---

public/fixtures/iiif/manifests/accompanying-canvas.json
public/fixtures/iiif/manifests/accompanying-placeholder-canvas.json
src/components/Painting/Painting.tsx
src/components/Player/Player.test.tsx
src/components/Player/Player.tsx
src/dev/manifests.ts

This updates our `<Player />` component for A/V canvases to now utilize any `placeholderCanvas` and/or `accompanyingCanvas` properties as the value for the `poster` attribute. There is potential for these to conflict and some logic has been built in to check for currentTime on the video element. If a conflict exists, the placeholder is used ONLY of if the currentTime is `0`.
The dev instance has three different Manifests to test from. Each of these should render a poster in the Video element. The first one, _accompanying/placeholder canvas_, will render the placeholderCanvas initially and then accompanyingCanvas while playing.
- accompanying/placeholder canvas
- accompanyingCanvas
- placeholderCanvas
Image placeholderCanvases should still function as previously designed with a …

Update `poster` attribute on A/V canvases.

---

serve.js

The dev server is continuously reloading because watch mode is set to `all`. This PR changes the watch to `change`, so it only reloads when there is a change in the file.  Related issue #122

fix live reload on dev server

---

pages/docs/label.mdx
pages/docs/metadata.mdx

This updates the Metadata docs.
---
I did this as-is for now but noticed an issue with how `metadata` outputs to `dl`, `dt`, `dd` elements that we may want to fix.
Issue is that each individual value entry does not have its own `dd` element. I think if we should probably fix this if we want to stick to semantic HTML as much as possible. This definitely is related to the customDelimiter.
**Current**
```html
<dl>
<div role="group" data-label="subject">
<dt>Subject</dt>
<dd>Masks, Commedia dell'arte,  Italian drama (Comedy),  Zanni (Fictitious character)</dd>
</div>
</dl>
```
**Proposed**
```html
<dl>
<div role="group" data-label="subject">
<dt>Subject</dt>
<dd>Masks</dd>
<dd>Commedia dell'arte</dd>
<dd>Italian drama (Comedy)</dd>
<dd>Zanni (Fictitious character)</dd>
</div>
</dl>
```

Updata Metadata docs.

---

.gitignore
README.md
package.json
pnpm-lock.yaml
vite.config.ts

Adds coverage reports in tests.   For the time being, I put some bare bones instructions in `README.md`.  Feel free @mathewjordan to place this where you like in the new docs.
Pull down the branch, do a `pnpm install`.
```shell
npm run test
```
```shell
npm run test --coverage
```
The coverage report uses [Vitest UI](https://vitest.dev/guide/ui.html). It will output a coverage report in the terminal, and open a nicer looking HTML coverage report as well.
Take a peek at `package.json` if you want to see the commands to see the coverage.

Coverage reports in tests

---

pages/docs/viewer.mdx
src/components/Viewer/Navigator/Cue.styled.tsx
src/components/Viewer/Navigator/Navigator.styled.tsx
src/components/Viewer/Painting/Painting.styled.tsx
src/components/Viewer/index.tsx
src/context/viewer-context.tsx
src/lib/xhr.ts

This adds the ability for customization of the request headers made by the Clover viewer. For example:
Noted in the revised documentation for the VIewer component:
> In some cases, a client may need to request Manifest or Collection resources with custom request headers, ex: `Authorization`. This can be done by passing a `requestHeaders` object to the `options` prop. This object will be passed to the request call made by the Viewer. Accepted **header** keys are defined in the [IncomingHttpHeaders](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/node/http.d.ts) interface.
Example:
```jsx
const iiifContent =
"https://api.dc.library.northwestern.edu/api/v2/works/8a833741-74a8-40dc-bd1d-c416a3b1bb38?as=iiif";
const token = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...";
return …
```

Support custom request headers, including `"Authorization": "Bearer ${token}"`

---

index.html
package.json
pages/index.mdx
src/components/Slider/Header/Control.styled.ts
src/components/Slider/Header/Header.styled.ts
src/components/Slider/Header/Header.tsx
src/components/Slider/Header/ViewAll.tsx
src/components/Viewer/Viewer/Header.styled.ts
src/components/Viewer/Viewer/Toggle.tsx
src/dev.tsx
src/styles/stitches.config.tsx

1. This adds the ability for us to test Clover components in a vite-spun environment without Nextra. This can be run by: `npm run dev:vite`.
2. Uses Lighthouse to assess accessibility of components, initial score be **82**.
3. Address issues:
- Name issue on information toggle (resolved with combination of arial-label and name attributes)
- Contrast issue on Slider header elements (resolved by combination of allowing inheriting header text color, and making our default accent color a bit darker)
- The remaining `dl` issue(s) are not actually a modern problem. It looks like Lighthouse uses an outdated spec in its analysis and does not account for [this ~2016 change](https://html.spec.whatwg.org/multipage/grouping-content.html#the-dl-element) that allows `div` groups of `dt` and `dd` values …

Add non-next dev ability. Address accessibility concerns.

---

src/components/Viewer/Player/AudioVisualizer.tsx
src/components/Viewer/Player/Player.tsx

- Fixes a bug which was overlaying the "audio visualizer" element on top of the `video` element when playing audio files, thereby not allowing a user to play audio files in the UI.
- Fix an audio visualizer component bug when a user clicks around to different time values in the `video` element
- Spin up the app in local dev environment
- Test this link and verify you can play the audio file in the UI, and the visualizer appears:
http://localhost:3000/docs/viewer/demo?iiif-content=https://iiif.io/api/cookbook/recipe/0002-mvm-audio/manifest.json

Bug fix to play audio files

---

src/components/Viewer/ImageViewer/OSD.tsx

The places the instance instantiation within a useEffect to ensure new instances are only created if the the URI of the image being loaded into OpenSeadragon changes.
Previous to this, any higher level re-renders of Clover were forcing a new UUID to be generated.

Address new OSD instantiation drift.

---

.gitignore
.vscode/settings.json
pages/docs/viewer.mdx
src/components/Viewer/ImageViewer/OSD.test.tsx
src/components/Viewer/ImageViewer/OSD.tsx
src/components/Viewer/InformationPanel/InformationPanel.test.tsx
src/components/Viewer/InformationPanel/InformationPanel.tsx
src/components/Viewer/Painting/Painting.tsx
src/components/Viewer/Painting/Placeholder.test.tsx
src/components/Viewer/Painting/Placeholder.tsx
src/components/Viewer/Player/Player.tsx
src/components/Viewer/Viewer/Content.test.tsx
src/components/Viewer/Viewer/Content.tsx
src/components/Viewer/Viewer/Header.tsx
src/components/Viewer/Viewer/Viewer.tsx

Adds CSS helper classes which consuming applications can target to further customize the Clover Viewer.
- General opinion on the class naming convention
- Run the test suite (tests added to verify class names exist and don't get knocked out of place)
@mathewjordan This might seem like a small change, but Clover commits to providing this vehicle for customization, its pretty important to clearly announce/document any changes to class names so as not to break client app styling.

Add CSS helper classes

---

src/components/Viewer/InformationPanel/Resource.tsx

Fixes this bug of infinite network requests on the VTT file (caused by including VTT helper package methods in `useEffect` dependency array...

Fix bug causing VTT infinite loop requests

---

src/components/Viewer/Viewer/Content.test.tsx
src/components/Viewer/Viewer/Content.tsx
src/components/Viewer/Viewer/Toggle.tsx
src/components/Viewer/Viewer/Viewer.tsx
tsconfig.json

Fixes a bug where Annotation Resources were being hidden when a user configures their `Viewer` to hide the `InformationPanel`.  For example, say there are VTT files associated with a Video in a `canvas`, these should always render alongside the content.
Configure the viewer to hide the `InformationPanel`, i.e.
```jsx
<Viewer
options={{
canvasHeight: "640px",
informationPanel: {
open: false,
renderAbout: false,
renderToggle: false,
},
}}
/>
```
If running Clover in a dev environment, use this manifest:
https://api.dc.library.northwestern.edu/api/v2/works/44f70212-029f-44cd-a3b3-03c18b208103?as=iiif
...or any manifest which contains Annotation Resources (doesn't have to be `VTT` annotations).

Always render annotation resources in Viewer

---

pages/docs/viewer.mdx
src/components/Viewer/Viewer/Content.test.tsx
src/components/Viewer/Viewer/Content.tsx
src/components/Viewer/Viewer/Viewer.tsx

Quick patch to account for a state where:
- `InformationPanel` open context value is `false`
- "About" in `InformationPanel` configured to be `true`
- No annotation resources exist
It results in the Viewer rendering an empty space where the `InformationPanel` displays (not good)
With default configuration, run in your dev environment and the initial render should not display empty space to the right of the Viewer Content:

Fix blank page aside rendering bug

---

pages/docs/viewer.mdx
pages/docs/viewer/demo.mdx
src/components/Viewer/Painting/Painting.styled.tsx
src/components/Viewer/Painting/Painting.tsx
src/components/Viewer/Painting/Placeholder.styled.tsx
src/components/Viewer/Player/Player.styled.tsx
src/components/Viewer/Viewer/Viewer.styled.tsx
src/components/Viewer/Viewer/Viewer.tsx
src/context/viewer-context.tsx

This work of mostly styling changes helps the Viewer component support automatic height within a wrapping container element. If an implementer uses either `100%` or `auto` as values for `options.canvasHeight` configuration, the viewer with be absolutely positioned, and extend to the bounds of the relative element. Internally in the Clover Viewer, a combination of flexbox `flex-grow` and `height` CSS attributes expand the canvas "painting" to fit these bounds. This will be applied to Image, Video, and Sound canvases.
This can be implemented as follows:
```jsx
<div style={{ position: "relative", height: "900px", zIndex: "0" }}>
<CloverViewer
iiifContent="https://example.org/iiif/manifest.json"
options={{ canvasHeight: "auto" }} // or "100%"
/>
</div>
```
Further documentation can be found …

Extend `canvasHeight` option for automatic height.

---

package.json
pnpm-lock.yaml
src/components/Scroll/Panel/Search/Results.tsx

This updates the Flexsearch dependency to latest and resolves an import issue noted by @ @tarjelavik in #193.

Update flexsearch dependency.

---

pages/docs/rendering.mdx
pages/index.mdx
src/components/Primitives/Rendering/Rendering.tsx
src/components/Primitives/index.tsx
src/components/Viewer/InformationPanel/About/About.tsx
src/components/Viewer/Properties/Rendering.test.tsx
src/components/Viewer/Properties/Rendering.tsx
src/components/Viewer/Properties/index.ts
src/dev.tsx
src/types/primitives.ts

Adds a basic rendering primitive for when you have a `resource that is an alternative, non-IIIF representation of the resource`. This just takes that thing and creates an anchor to the external resource similar to how things work with `SeeAlso`.

Add Rendering primitive.

---

pages/docs/viewer.mdx
src/components/UI/Icon/Icon.tsx
src/components/UI/Icons/Download.tsx
src/components/UI/Icons/index.tsx
src/components/Viewer/InformationPanel/InformationPanel.tsx
src/components/Viewer/Viewer/Content.tsx
src/components/Viewer/Viewer/Download.styled.ts
src/components/Viewer/Viewer/Download.test.tsx
src/components/Viewer/Viewer/Download.tsx
src/components/Viewer/Viewer/Header.styled.ts
src/components/Viewer/Viewer/Header.tsx
src/context/viewer-context.tsx
src/fixtures/iiif-cookbook/0046-rendering.json
src/fixtures/viewer/rendering/manifest-with-renderings.json
src/hooks/use-iiif/useRendering.ts
src/hooks/useViewerDownload.tsx
src/setupTests.ts
src/types/presentation-3.ts

Adds a UI popover feature to download items present in a Manifest and Canvas's `rendering` property:
https://iiif.io/api/cookbook/recipe/0046-rendering/
The download button will display by default, but you can configure the Viewer to not display it also:
```jsx
<Viewer
options={{
showDownload: false,
canvasHeight: "500px",
...
}}
/>
```
Start up a local Clover instance, navigate to: http://localhost:3000/docs/viewer/demo and test any manifest with `rendering` either at the root, or within a canvas.  Here are two example manifests:
- https://iiif.io/api/cookbook/recipe/0046-rendering/manifest.json
- https://figgy.princeton.edu/concern/scanned_resources/f93c3171-43a6-4db3-9692-ba394d669320/manifest

Support download of manifest and canvas rendering property items

---

src/components/Viewer/Viewer/Download.test.tsx
src/components/Viewer/Viewer/Download.tsx
src/fixtures/viewer/rendering/manifest-without-renderings.json

Patch fix for the rendering download button display to only show if rendering items exist on a manifest.  For example, this manifest has no `rendering` properties.
- Run the app locally and in the Viewer Demo page, load any manifest which does not contain `rendering` properties.
- Verify the download button does not display

Patch fix for the rendering download button

---

package.json
pnpm-lock.yaml
src/components/Image/OSD/OSD.tsx

This addresses issue #203 raised by @wykhuh. In some instances when navigating canvases of a manfiest, the expected IIIF tiled images is not drawn to the canvas and the previous item is retained. The actual occurance is a collision on the index of the canvas where the IIIF tiled image is strangely drawn under the previous tiled image that was somehow retained. In addition to the redraw, we now also update a timing issue where the `osdUri` is not reset unless the `openSeadragon` instance exists.
To resolve, we are now forcing a redraw prior to the drawing of the new image.
This also updates the `openseadragon` dependency as previous IIIF tile size issues have now been resolved in the recent release 4.1.1.

Force redraw to destroy previous tiled image.

---

src/components/Image/OSD/OSD.tsx

This addresses #205, caused by an issue in React strict mode where new openseadragon instances are opened on each re-render. This work sets a ref to initialize the the component, and then OSD.tsx will not instantiate a `new OpenSeadragon.Viewer()` if this ref is `true`.
This issue is best tested external to the Nextra docs.

Initialize new openseadragon instance once.

---

src/components/Viewer/Viewer/Download.styled.ts

Align the download icon.

---

pages/docs/slider.mdx
src/components/Slider/index.tsx
src/types/slider.ts

This adds a `options.customViewAll` property for overriding or setting custom `homepage` id.

Add custom View All property for overriding slider homepage.

---

src/components/Viewer/Media/Media.test.tsx
src/components/Viewer/Media/Media.tsx
src/components/Viewer/Media/Thumbnail.test.tsx
src/components/Viewer/Media/Thumbnail.tsx

This sets the default label for canvas figures (thumbnails) in the media component in cases where the Canvas does not have a label. The label will be the `(index + 1).toString()` to accommodate all languages. This same label will be the `alt` of the rendered thumbnail as well. Filtering will also work in this cases, ex: "2" as the input value will be show the "2", "12", "21", "22", etc... thumbnails.
Review with this fixture
https://samvera-labs.github.io/clover-iiif/docs/viewer/demo?iiif-content=https%3A%2F%2Fmarkpbaggett.github.io%2Fstatic_iiif%2Fmanifests%2Ftests%2Fservice_maps_0103.json
- Canvas thumbnails will render as "1" and "2'.
- Canvases are filterable

Set default labels as index + 1 for canvas figures.

---

pages/docs/scroll.mdx
src/components/Scroll/Figure/Figure.styled.tsx
src/components/Scroll/Figure/Figure.tsx
src/components/Scroll/Figure/ImageViewer.styled.tsx
src/components/Scroll/Figure/Thumbnail.test.tsx
src/components/Scroll/Figure/Thumbnail.tsx
src/components/Scroll/Items/Item.tsx
src/components/Scroll/Items/Items.styled.tsx
src/components/Scroll/Items/Items.tsx
src/context/scroll-context.tsx

This extends Figure related `options` for the Scroll component. Completing this allows implementers of Scroll to customize the canvas figures as required, giving more our less screen space to the figure, and provides flexibility on how the figure is rendered.
Users can now customize: 
- `options.figure.aspectRatio` default: **1.618** (golden ratio)
- `options.figure.display` default: **image-viewer**
- `options.figure.width` default: **38.2%**
As an enum, the other option for display is **thumbnail**. 
1. Install dependencies if required
2. Spin up local dev `npm run dev`
3. Navigate to Scroll demo http://localhost:3000/docs/scroll/demo
4. Edit the `demo.mdx` page at `pages/docs/scroll/demo.mdx`, replacing Scroll JSX with:
```mdx
<Scroll …
```

Add figure customization options

---

package-lock.json
package.json
src/components/Viewer/Media/Thumbnail.tsx

Adds `react-lazy-load-image-component` and modifies `src/components/Viewer/Media/Thumbnail.tsx` to use it.   I don't know anything about the source of the code other than it seems popular.    Lazy loading was requested in issue #86.
Tested on a ~1200 page manifest ( https://collections.library.yale.edu/manifests/30675510 ) and performance seemed good on Mac Safari, Chrome, and Firefox.   Could use further real-world testing on mobile devices.

Lazily load viewer thumbnails

---

pages/docs/viewer.mdx
src/components/Viewer/index.tsx
src/context/viewer-context.tsx

Hey there!
This is a pull request to add support for replacing the default loading UI ("Loading") with a React component. The idea is from this issue: https://github.com/samvera-labs/clover-iiif/issues/245
I had to use React.ComponentType as opposed to the more flexible ReactNode because ReactNode caused an infinite loop in the `deepMerge` function.
In the [issue thread](https://github.com/samvera-labs/clover-iiif/issues/245), it was mentioned that a new default loading state would be nice. I'm open to implementing that! For example, we could do [some sort of skeleton](https://ui.shadcn.com/docs/components/skeleton). If we do implement a skeleton, let me know how detailed it should be (big rectangle vs lots of smaller shapes).

Add support for a custom loading component

---

src/components/Image/Controls/Controls.tsx

When users click the "reset" button, the rotation is set back to it's original rotation
- Adds `setRotation` to `"home"` event
https://www.loom.com/share/7422e538729947fb93461116b282da15?sid=2e446fa1-7bc7-4cf5-a0aa-016b3c4b0145

Add rotation reset to reset button

---

src/components/Viewer/Viewer/Viewer.styled.tsx

We noticed this in https://github.com/pulibrary/figgy/issues/6351. My
initial tests show this should fix it, but I honestly don't know how to
get a test release into my app to see for sure.
This might fix #214

Fix mobile display stretching past bounding box in mobile.

---

pages/docs/viewer.mdx
pages/docs/viewer/demo.mdx
src/components/Viewer/InformationPanel/About/About.styled.ts
src/components/Viewer/InformationPanel/InformationPanel.styled.tsx
src/components/Viewer/InformationPanel/InformationPanel.tsx
src/components/Viewer/Viewer/Content.tsx
src/components/Viewer/Viewer/Header.tsx
src/components/Viewer/Viewer/Toggle.styled.ts
src/components/Viewer/Viewer/Toggle.tsx
src/components/Viewer/Viewer/Viewer.styled.tsx
src/components/Viewer/Viewer/Viewer.tsx
src/i18n/locales/en.json

This gem addresses a responsive issues relating to legacy ideas for the Information Panel component. Previously, the information panel was treated very differently in smaller view ports, forcing the viewer to go to `position: fixed`. This is no longer desired as it grants Clover too much control over the screen within a consuming application. With the @tpendragon and Princeton's need of Clover to reside within a relative container wrapping it if `options.canvasHeight: "100%"` is set, this convention presents additional complications.
- This work advances Clover by treating the Toggle the same regardless of viewport size. 
- In `@sm` viewports, the expanded Information Panel `aside` now slides completely over the viewer, overtaking width and height of the the content space provided.
- In …

Refine information panel toggle, address responsive issues.

---

pages/docs/image.mdx
public/manifest/behavior/paged.json
src/components/Image/OSD/OSD.tsx
src/components/Image/index.tsx
src/components/UI/Tag/Tag.tsx
src/components/Viewer/Media/Controls.styled.tsx
src/components/Viewer/Media/Controls.tsx
src/components/Viewer/Media/Media.styled.tsx
src/components/Viewer/Media/Media.tsx
src/components/Viewer/Media/Thumbnail.styled.tsx
src/components/Viewer/Media/Thumbnail.test.tsx
src/components/Viewer/Media/Thumbnail.tsx
src/components/Viewer/Painting/Painting.test.tsx
src/components/Viewer/Painting/Painting.tsx
src/components/Viewer/Painting/Placeholder.styled.tsx
src/components/Viewer/Painting/Placeholder.test.tsx
src/components/Viewer/Painting/Placeholder.tsx
src/components/Viewer/Viewer/Content.tsx
src/components/Viewer/Viewer/Viewer.tsx
src/components/Viewer/index.tsx
src/context/viewer-context.tsx
src/hooks/use-iiif/index.ts
src/lib/openseadragon-helpers.ts
src/lib/retry.ts

This work introduces handling of the `behavior` property, allowing the **Viewer** component to handle the [Simple Manifest - Book](https://iiif.io/api/cookbook/recipe/0009-book-1/) recipe for a 2-up view. As part of this work, the **Image** component can now handle `src` OR `body` properties as `string` or `string[]`. The Image component will automatically arrange each canvas resource adjacent to one another on the `x` axis. It will also normalize the height of each item automatically. A yet to be determined future feature could make this normalization functionality optional. 
**Clover Viewer rendering Simple Manifest - Book recipe**
- [Recipe](https://iiif.io/api/cookbook/recipe/0009-book-1)
- [Manifest](https://iiif.io/api/cookbook/recipe/0009-book-1/manifest.json)
**Clover Viewer …

Handle behavior for `paged` 2-up view as well as `continuous`

---

pages/docs/viewer.mdx
src/components/Viewer/Player/Player.tsx
src/context/viewer-context.tsx

This updates the `crossorigin` attribute assigned to videos. Previously all AV material was assumed to be `crossigin: "anonymous"`. This was restrictive and assumed proper CORS arrangements were made on all providers. This hampered material served through the Internet Archive, related: https://github.com/internetarchive/iiif/issues/109.
The default is now `undefined` and can be modified as required at `configOptions.crossOrigin` which corresponds to enums described at https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Attributes/crossorigin.

Update crossOrigin pattern for videos.

---

src/components/Viewer/InformationPanel/About/About.styled.ts

Adjusts overflow behavior to show scrollbar only when content is clipped.

Hotfix: show interior scrollbars only when necessary

---

src/components/Slider/Items/Items.tsx
src/components/UI/LazyLoad/LazyLoad.test.tsx
src/components/UI/LazyLoad/LazyLoad.tsx

This work adds a LazyLoad wrapper component using InteractionObserver  around the Slider entries to prevent large collections from overpopulating the DOM on intial load.

Hotfix: Add lazy loading to slider component entries.

---

docs/components/DynamicImports/Viewer.tsx
pages/docs/viewer/_meta.json
pages/docs/viewer/content-state.mdx
public/manifest/content-state/fragment-selector-video.json
public/manifest/content-state/point-selector.json
src/components/Viewer/InformationPanel/Annotation/Item.tsx
src/components/Viewer/InformationPanel/Annotation/VTT/Cue.tsx
src/components/Viewer/InformationPanel/Annotation/VTT/VTT.tsx
src/components/Viewer/Painting/Painting.tsx
src/components/Viewer/Player/Player.tsx
src/components/Viewer/index.tsx
src/context/viewer-context.tsx
src/lib/iiif.ts

This work adds in the ability for the Viewer component to return its current _Content State_ through the `contentStateCallback` prop. If enabled the an object is returned to the consuming application containing both an encoded Content State as well as the raw JSON. The consuming application can then handle this however is required for its use case(s). This can be valuable for sharing the current content state with other human users or for communicating with other IIIF-fluent components in their application.
Implementation:
```jsx
const MyViewerComponent = () => {
const handleContentStateCallback = (contentState) => {
console.log(contentState);
};
return (
<Viewer
contentStateCallback={handleContentStateCallback}
iiifContent="https://api.dc.library.northwestern.edu/api/v2/works/71153379-428 …
```

Add content state callback.

---

src/components/Viewer/Viewer/Content.tsx

Similar to when a VTT is present, we want to render the content state annotations in the information panel. This Work overrides the config to force the `aside` panel to render if a contentStateAnnotation is present in the viewer context.

Set information panel to be forced open if content state annotations are present.

---

pages/docs/viewer.mdx
pages/docs/viewer/_meta.json
pages/docs/viewer/prefetched.mdx
src/components/Viewer/index.tsx
src/lib/iiif.test.ts
src/lib/iiif.ts

This work adds the ability for the `iiifContent` prop to accept IIIF Manifests and Collections as JSON objects. In some use cases applications may already have these resources ready to feed to a viewer and do not want to make additional requests on the the `id`. This work accounts for manual upgrading of Presentation 2.x resources to 3.0 if required. It then sideloads the resource into `vault`. 
If spinning up a Clover locally, navigate to the hidden page of http://localhost:3000/docs/viewer/prefetched. On this page, a resource will be loading. Note that no additional XHR request is made on the Manifest.

Add ability to accept prefetched JSON as `iiifContent`

---

pages/docs/viewer.mdx
pnpm-lock.yaml
src/components/Image/OSD/OSD.tsx

When OpenSeadragon is initiated, this checks the boolean value of `options.openSeadragon.gestureSettingsMouse.scrollToZoom`. If `false`, we set an event handler on `canvas-scroll` and remove the preventDefault override that is set within OpenSeadragon. This allows the browser window to be scrolled and not be captured by the OpenSeadragon canvas. 
Additional docs have been added detailing how a user can set Scroll to Zoom to true if this use case is necessary.
Go to docs pages and view any image manifest in the demo. By default `scrollToZoom` is false and the scrolling of the page will occur when cursor is over an active openseadragon canvas.

Prevent default cursor capture when OSD scrollToZoom is false.

---

pages/docs/viewer.mdx
src/components/Viewer/InformationPanel/InformationPanel.tsx
src/context/viewer-context.tsx

This add an override for the Annotations tab label. The label is normally defined by the `i18n/[language].json` file. In some cases users may way to override this label.

Add property for annotations tab label override.
